export const ITEMS = [
  {
    id: '1',
    name: 'Pão de queijo',
    categories: ['5° andar', '7° andar'],
    description: 'Pão de queijo quentinho e saboroso, feito na hora com queijo mineiro.',
    price: 'R$ 5,00',
    priceNum: 5.0,
    image: 'https://amopaocaseiro.com.br/wp-content/uploads/2022/08/yt-069_pao-de-queijo_receita.jpg',
    emoji: '🧀',
  },
  {
    id: '2',
    name: 'Hamburgão de cheddar',
    categories: ['5° andar', '7° andar'],
    description: 'Hamburgão suculento com queijo cheddar derretido, alface e tomate.',
    price: 'R$ 12,00',
    priceNum: 12.0,
    image: 'https://i.ytimg.com/vi/KMWn8PfBWbE/hq720.jpg',
    emoji: '🍔',
  },
  {
    id: '3',
    name: 'Coxinha',
    categories: ['5° andar'],
    description: 'Coxinha crocante por fora com recheio cremoso de frango por dentro.',
    price: 'R$ 6,00',
    priceNum: 6.0,
    image: 'https://blog.winesofargentina.com/wp-content/uploads/2021/09/Coxinhas_apertura.jpg',
    emoji: '🍗',
  },
  {
    id: '4',
    name: 'Pão na Chapa',
    categories: ['7° andar'],
    description: 'Pão francês na chapa com manteiga derretida. Simples e delicioso.',
    price: 'R$ 4,50',
    priceNum: 4.5,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoniJjkbQv8dhBl3N2BAF5MzI73jc4Es3blMElCQFdT56-GzcuJxqblp_PjESi8354bS-XbJHR8CaA6qmI0DkUj3G7JOxsHbAla3QD0GE&s=10',
    emoji: '🍞',
  },
  {
    id: '5',
    name: 'Mistinho quente',
    categories: ['5° andar'],
    description: 'Enroladinho quente de presunto e queijo, assado na hora.',
    price: 'R$ 8,00',
    priceNum: 8.0,
    image: 'https://essareceitafunciona.com.br/wp-content/uploads/2022/12/Enroladinho-de-presunto-e-queijo-Essa-Receita-Funciona-9.jpg',
    emoji: '🥐',
  },
  {
    id: '6',
    name: 'Esfiha de carne',
    categories: ['5° andar', '7° andar'],
    description: 'Esfiha com recheio de carne moída temperada, assada na hora.',
    price: 'R$ 7,50',
    priceNum: 7.5,
    image: 'https://i.ytimg.com/vi/qGAKtTVTOLA/hq720.jpg',
    emoji: '🫓',
  },
];
